import type { Project, FoodDonation, ServiceDonation } from "./types"

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Emergency Food Relief for Rural Communities",
    description:
      "Providing immediate food assistance to families affected by drought in rural Kenya. This project aims to distribute nutritious meals and essential food supplies to 500 families over the next 3 months.",
    shortDescription: "Emergency food relief for drought-affected families in rural Kenya",
    ngoId: "ngo-1",
    ngoName: "Kenya Relief Foundation",
    targetAmount: 25000,
    raisedAmount: 18750,
    goalMeals: 15000,
    providedMeals: 11250,
    status: "active",
    category: "Emergency Relief",
    location: "Turkana County, Kenya",
    imageUrl: "/rural-community-food-distribution-kenya.png",
    createdAt: "2024-01-15T00:00:00Z",
    endDate: "2024-04-15T00:00:00Z",
    verified: true,
  },
  {
    id: "2",
    title: "School Feeding Program - Urban Schools",
    description:
      "Supporting nutritious school meals for children in underserved urban areas. This program ensures that 1,200 students receive daily meals, improving their health and educational outcomes.",
    shortDescription: "Daily nutritious meals for 1,200 urban school children",
    ngoId: "ngo-2",
    ngoName: "Education & Nutrition Alliance",
    targetAmount: 40000,
    raisedAmount: 32000,
    goalMeals: 36000,
    providedMeals: 28800,
    status: "active",
    category: "Education & Nutrition",
    location: "Nairobi, Kenya",
    imageUrl: "/school-children-eating-lunch-classroom.png",
    createdAt: "2024-02-01T00:00:00Z",
    endDate: "2024-12-31T00:00:00Z",
    verified: true,
  },
  {
    id: "3",
    title: "Community Garden Initiative",
    description:
      "Establishing sustainable community gardens to provide fresh produce for local families while teaching agricultural skills. This long-term project will benefit 200 households.",
    shortDescription: "Sustainable community gardens for 200 households",
    ngoId: "ngo-3",
    ngoName: "Green Communities Initiative",
    targetAmount: 15000,
    raisedAmount: 8500,
    goalMeals: 24000,
    providedMeals: 13600,
    status: "active",
    category: "Sustainable Agriculture",
    location: "Kisumu, Kenya",
    imageUrl: "/community-garden-vegetables-farming.png",
    createdAt: "2024-01-20T00:00:00Z",
    endDate: "2024-08-20T00:00:00Z",
    verified: true,
  },
]

export const mockFoodDonations: FoodDonation[] = [
  {
    id: "food-1",
    providerId: "provider-1",
    title: "Fresh Vegetables - Daily Surplus",
    description:
      "Daily surplus of fresh vegetables including tomatoes, onions, carrots, and leafy greens. All produce is fresh and suitable for immediate consumption.",
    category: "fresh-produce",
    quantity: 50,
    unit: "kg",
    expiryDate: "2024-01-25T00:00:00Z",
    pickupLocation: "Green Valley Market, Westlands, Nairobi",
    pickupTimeStart: "18:00",
    pickupTimeEnd: "20:00",
    status: "available",
    imageUrl: "/fresh-vegetables-market-surplus.png",
    createdAt: "2024-01-24T10:00:00Z",
  },
  {
    id: "food-2",
    providerId: "provider-2",
    title: "Packaged Rice and Beans",
    description:
      "Surplus packaged rice and beans from our restaurant. All items are sealed and within expiry dates. Perfect for family meals.",
    category: "packaged-food",
    quantity: 25,
    unit: "packages",
    expiryDate: "2024-02-15T00:00:00Z",
    pickupLocation: "Mama Njeri Restaurant, CBD, Nairobi",
    pickupTimeStart: "21:00",
    pickupTimeEnd: "22:30",
    status: "available",
    imageUrl: "/packaged-rice-beans-restaurant.png",
    createdAt: "2024-01-24T15:30:00Z",
  },
]

export const mockServiceDonations: ServiceDonation[] = [
  {
    id: "service-1",
    donorId: "donor-1",
    title: "Nutrition Education Workshops",
    description:
      "Offering free nutrition education workshops for communities. I am a certified nutritionist with 5 years of experience in community health programs.",
    skills: ["Nutrition Education", "Community Health", "Workshop Facilitation"],
    hoursAvailable: 20,
    location: "Nairobi and surrounding areas",
    availability: "Weekends and evenings",
    status: "available",
    createdAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "service-2",
    donorId: "donor-2",
    title: "Food Distribution Logistics Support",
    description:
      "Providing logistics support for food distribution events. I have a truck and experience in coordinating community food drives.",
    skills: ["Logistics", "Transportation", "Event Coordination"],
    hoursAvailable: 15,
    location: "Nairobi Metropolitan Area",
    availability: "Flexible schedule",
    status: "available",
    createdAt: "2024-01-22T00:00:00Z",
  },
]
